/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/avatar.glb --output src/components/Avatar.jsx -r public
*/

import { useRef, useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { useCharacterAnimations } from "../hooks/useCharacterAnimations";

const AVATAR_URL = "/models/avatar.glb";
// Voir la note sur Draco vs meshopt dans Office.tsx.
const DRACO_PATH = "/draco/";
const ANIMATIONS_URL = "/animations/animations.glb";

/**
 * L'ordre fait foi : `animationIndex` (piloté par Experience et Projects) est
 * un index dans ce tableau. Nommer explicitement les clips évite de dépendre
 * de l'ordre dans lequel le loader les renvoie.
 */
const ANIMATION_NAMES = [
  "Typing",
  "Standing",
  "Falling",
  "Waving",
  "Pointing",
  "Walking",
] as const;

type AvatarProps = {
  animation?: string;
};
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Body: THREE.SkinnedMesh;
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh;
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh;
    Wolf3D_Outfit_Top: THREE.SkinnedMesh;
    Wolf3D_Hair: THREE.SkinnedMesh;
    EyeLeft: THREE.SkinnedMesh;
    EyeRight: THREE.SkinnedMesh;
    Wolf3D_Head: THREE.SkinnedMesh;
    Wolf3D_Teeth: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    Wolf3D_Body: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial;
    Wolf3D_Hair: THREE.MeshStandardMaterial;
    Wolf3D_Eye: THREE.MeshStandardMaterial;
    Wolf3D_Skin: THREE.MeshStandardMaterial;
    Wolf3D_Teeth: THREE.MeshStandardMaterial;
  };
};

export function Avatar({ animation, ...props }: AvatarProps) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(AVATAR_URL, DRACO_PATH) as GLTFResult;
  // Anciennement pilotés par leva : le panneau de debug embarquait toute la
  // librairie dans le bundle de prod pour deux booléens désactivés.
  const headFollow = false;
  const cursorFollow = false;
  // Les 6 clips sont regroupés dans un seul .glb (rééchantillonné + meshopt) :
  // 1 requête de 346 kB au lieu de 6 FBX pour 4,7 Mo.
  const { animations } = useGLTF(ANIMATIONS_URL, DRACO_PATH);
  const characterAnimations = useCharacterAnimations();
  const { actions } = useAnimations(animations, group);

  // Vecteur réutilisé : allouer un Vector3 par frame nourrit le GC pour rien.
  const lookAtTarget = useRef(new THREE.Vector3());

  useFrame((state) => {
    // Rien à faire dans la boucle si aucun suivi n'est actif.
    if (!headFollow && !cursorFollow) return;

    // headFollow will make the head look at the camera position
    if (headFollow)
      group.current
        ?.getObjectByName("Head")
        ?.lookAt(state.mouse.x, state.mouse.y, 20);

    // cursorFollow will make the head look at the cursor position
    if (cursorFollow) {
      lookAtTarget.current.set(state.mouse.x, state.mouse.y, 1);
      group.current?.getObjectByName("Spine2")?.lookAt(lookAtTarget.current);
    }
  });
  useEffect(() => {
    const name = ANIMATION_NAMES[characterAnimations?.animationIndex ?? 0];
    const action = actions[name];
    action?.reset().fadeIn(0.5).play();
    return () => {
      action?.fadeOut(0.5);
    };
  }, [actions, characterAnimations?.animationIndex]);

  // useEffect(() => {
  //   Object.values(materials).forEach((material) => {
  //     material.wireframe = wireframe;
  //   });
  // }, [wireframe]);

  return (
    <group
      {...props}
      ref={group as React.Ref<THREE.Group> | undefined}
      dispose={null}
    >
      <group name="Armature" rotation-x={-Math.PI / 2}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Body"
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Outfit_Bottom"
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Outfit_Footwear"
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Outfit_Top"
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Hair"
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
        <skinnedMesh
          frustumCulled={false}
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

// Préchargés dès l'import du module : les fetchs partent en parallèle du
// bundle, sans attendre le montage de l'avatar.
useGLTF.preload(AVATAR_URL, DRACO_PATH);
useGLTF.preload(ANIMATIONS_URL, DRACO_PATH);
