/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/room.gltf --output src/components/Room.jsx -r public
*/

import * as THREE from "three";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import { useThree } from "@react-three/fiber";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import MergedMeshes from "./WebGL/MergedMeshes";
type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Body: THREE.SkinnedMesh;
    Wolf3D_Hair: THREE.SkinnedMesh;
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh;
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh;
    Wolf3D_Outfit_Top: THREE.SkinnedMesh;
    EyeLeft: THREE.SkinnedMesh;
    EyeRight: THREE.SkinnedMesh;
    Wolf3D_Head: THREE.SkinnedMesh;
    Wolf3D_Teeth: THREE.SkinnedMesh;
    Cubone_1: THREE.Mesh;
    Cubone_2: THREE.Mesh;
    Cubone_3: THREE.Mesh;
    Cubone_4: THREE.Mesh;
    Cubone_5: THREE.Mesh;
    Desk_1: THREE.Mesh;
    Desk_2: THREE.Mesh;
    Desk_3: THREE.Mesh;
    Desk_4: THREE.Mesh;
    Desk_5: THREE.Mesh;
    GamerChair: THREE.Mesh;
    Houseplant_7: THREE.Mesh;
    Houseplant_7_1: THREE.Mesh;
    Houseplant_7_2: THREE.Mesh;
    Keyboard_1: THREE.Mesh;
    Keyboard_2: THREE.Mesh;
    Keyboard_3: THREE.Mesh;
    Keyboard_4: THREE.Mesh;
    Lamp_1: THREE.Mesh;
    Lamp_2: THREE.Mesh;
    Lamp_3: THREE.Mesh;
    Mouse: THREE.Mesh;
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
    ["Node-Mesh_2"]: THREE.Mesh;
    ["Node-Mesh_3"]: THREE.Mesh;
    ["Node-Mesh_4"]: THREE.Mesh;
    ["Node-Mesh_5"]: THREE.Mesh;
    SM_ShelfSM_Shelf1_1: THREE.Mesh;
    SM_ShelfSM_Shelf1_1_1: THREE.Mesh;
    Shelf_Clutter_1: THREE.Mesh;
    Shelf_Clutter_2: THREE.Mesh;
    Shelf_Clutter_3: THREE.Mesh;
    Shelf_Clutter_4: THREE.Mesh;
    Shelf_Clutter_5: THREE.Mesh;
    Shelf_Clutter_6: THREE.Mesh;
    Shelf_Clutter_7: THREE.Mesh;
    Shelf_Clutter_8: THREE.Mesh;
    Shelf_Clutter_9: THREE.Mesh;
    Shelf_Clutter_10: THREE.Mesh;
    Shelf_Clutter_11: THREE.Mesh;
    Shelf_Clutter_12: THREE.Mesh;
    Shelf_Clutter_13: THREE.Mesh;
    Shelf_Clutter_14: THREE.Mesh;
    Shelf_Clutter_15: THREE.Mesh;
    speaker004: THREE.Mesh;
    speaker004_1: THREE.Mesh;
    ["Cube-Mesh"]: THREE.Mesh;
    ["Cube-Mesh_1"]: THREE.Mesh;
    ["Cube-Mesh_2"]: THREE.Mesh;
    CoffeTable_1: THREE.Mesh;
    CoffeTable_2: THREE.Mesh;
    iMac_1: THREE.Mesh;
    iMac_1_1: THREE.Mesh;
    Cardboard_Boxes_1: THREE.Mesh;
    Cardboard_Boxes_2: THREE.Mesh;
    DrumSet1: THREE.Mesh;
    DrumSet1_1: THREE.Mesh;
    DrumSet1_2: THREE.Mesh;
    DrumSet1_3: THREE.Mesh;
    DrumSet1_4: THREE.Mesh;
    DrumSet1_5: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Screen: THREE.Mesh;
    Hips: THREE.Bone;
  };
  materials: {
    ["Wolf3D_Body.004"]: THREE.MeshStandardMaterial;
    ["Wolf3D_Hair.004"]: THREE.MeshStandardMaterial;
    ["Wolf3D_Eye.004"]: THREE.MeshStandardMaterial;
    ["Wolf3D_Outfit_Footwear.004"]: THREE.MeshStandardMaterial;
    ["Wolf3D_Skin.004"]: THREE.MeshStandardMaterial;
    Floor2: THREE.MeshStandardMaterial;
  };
};

const OFFICE_URL = "/models/office.glb";
// Compression Draco, décodeur servi en local (pas de CDN tiers).
//
// À ne PAS remplacer par meshopt : meshopt quantifie les positions et pose le
// transform de dé-quantification sur chaque noeud, alors que ce composant
// (généré par gltfjsx) ne lit que `nodes.X.geometry` en ignorant les
// transforms — la pièce se retrouve disloquée. Draco, lui, restitue les
// positions dans le repère d'origine.
const DRACO_PATH = "/draco/";

export function Office({
  ...props
}: JSX.IntrinsicElements["group"] & { section: number }) {
  const { section } = props;
  const { nodes } = useGLTF(OFFICE_URL, DRACO_PATH) as GLTFResult;
  const gl = useThree((state) => state.gl);
  const texture = useTexture("textures/Baked.jpg");
  const textureVSCode = useVideoTexture("textures/vscode.mp4");

  // Réglages de texture : une seule fois, pas à chaque render.
  useEffect(() => {
    texture.flipY = false;
    texture.colorSpace = THREE.SRGBColorSpace;
    // Le lightmap est vu de biais : l'anisotropie évite le flou en rasance,
    // bornée à ce que le GPU sait faire.
    texture.anisotropy = Math.min(4, gl.capabilities.getMaxAnisotropy());
    texture.needsUpdate = true;
  }, [texture, gl]);

  useEffect(() => {
    textureVSCode.center.set(4, 6);
  }, [textureVSCode]);

  // Un seul matériau pour toute la pièce, créé une fois et libéré au démontage.
  // L'éclairage étant déjà cuit dans la texture, MeshBasicMaterial suffit :
  // il évite le calcul PBR sur chaque fragment de la scène.
  const textureMaterial = useMemo(
    () =>
      new THREE.MeshBasicMaterial({
        map: texture,
        transparent: true,
        opacity: 0,
      }),
    [texture]
  );

  useEffect(() => () => textureMaterial.dispose(), [textureMaterial]);

  const textureOpacity = useMotionValue(0);
  // Quand la pièce est totalement transparente, on la sort du rendu :
  // plus de draw call ni de tri de transparence pour les sections 1 à 3.
  const [roomVisible, setRoomVisible] = useState(true);
  const visibleRef = useRef(true);

  useEffect(() => {
    // On remplace le useFrame (qui tournait 60 fois/s en permanence) par un
    // abonnement : le matériau n'est touché que pendant la transition.
    // Note : on ne touche pas à `transparent`, qui forcerait une recompilation
    // du shader à chaque changement.
    const unsubscribe = textureOpacity.on("change", (value) => {
      textureMaterial.opacity = value;
      // setState seulement quand le booléen bascule vraiment, sinon on
      // provoquerait un render React à chaque frame du fondu.
      const visible = value > 0.001;
      if (visible !== visibleRef.current) {
        visibleRef.current = visible;
        setRoomVisible(visible);
      }
    });
    return unsubscribe;
  }, [textureOpacity, textureMaterial]);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0, {
      duration: 0.8,
    });
  }, [section, textureOpacity]);

  // La décompression vidéo consomme du CPU/GPU en continu : on la met en pause
  // dès que l'écran n'est plus regardé.
  useEffect(() => {
    const video = textureVSCode.image as HTMLVideoElement | undefined;
    if (!video) return;
    if (section === 0) video.play().catch(() => {});
    else video.pause();
  }, [section, textureVSCode]);

  // Géométries regroupées par bloc : chaque tableau devient un seul draw call.
  const geometries = useMemo(
    () => ({
      plane: [nodes.Plane_1.geometry, nodes.Plane_2.geometry],
      coffeeTable: [nodes.CoffeTable_1.geometry, nodes.CoffeTable_2.geometry],
      cubone: [
        nodes.Cubone_1.geometry,
        nodes.Cubone_2.geometry,
        nodes.Cubone_3.geometry,
        nodes.Cubone_4.geometry,
        nodes.Cubone_5.geometry,
      ],
      desk: [
        nodes.Desk_1.geometry,
        nodes.Desk_2.geometry,
        nodes.Desk_3.geometry,
        nodes.Desk_4.geometry,
        nodes.Desk_5.geometry,
      ],
      speaker: [nodes.speaker004.geometry, nodes.speaker004_1.geometry],
      switchConsole: [
        nodes["Cube-Mesh"].geometry,
        nodes["Cube-Mesh_1"].geometry,
        nodes["Cube-Mesh_2"].geometry,
      ],
      imac: [nodes.iMac_1.geometry, nodes.iMac_1_1.geometry],
      boxes: [
        nodes.Cardboard_Boxes_1.geometry,
        nodes.Cardboard_Boxes_2.geometry,
      ],
      drum: [
        nodes.DrumSet1.geometry,
        nodes.DrumSet1_1.geometry,
        nodes.DrumSet1_2.geometry,
        nodes.DrumSet1_3.geometry,
        nodes.DrumSet1_4.geometry,
        nodes.DrumSet1_5.geometry,
      ],
      keyboard: [
        nodes.Keyboard_1.geometry,
        nodes.Keyboard_2.geometry,
        nodes.Keyboard_3.geometry,
        nodes.Keyboard_4.geometry,
      ],
      lamp: [
        nodes.Lamp_1.geometry,
        nodes.Lamp_2.geometry,
        nodes.Lamp_3.geometry,
      ],
      shelf: [
        nodes.SM_ShelfSM_Shelf1_1.geometry,
        nodes.SM_ShelfSM_Shelf1_1_1.geometry,
      ],
      shelfClutter: [
        nodes.Shelf_Clutter_1.geometry,
        nodes.Shelf_Clutter_2.geometry,
        nodes.Shelf_Clutter_3.geometry,
        nodes.Shelf_Clutter_4.geometry,
        nodes.Shelf_Clutter_5.geometry,
        nodes.Shelf_Clutter_6.geometry,
        nodes.Shelf_Clutter_7.geometry,
        nodes.Shelf_Clutter_8.geometry,
        nodes.Shelf_Clutter_9.geometry,
        nodes.Shelf_Clutter_10.geometry,
        nodes.Shelf_Clutter_11.geometry,
        nodes.Shelf_Clutter_12.geometry,
        nodes.Shelf_Clutter_13.geometry,
        nodes.Shelf_Clutter_14.geometry,
        nodes.Shelf_Clutter_15.geometry,
      ],
      houseplant: [
        nodes.Houseplant_7.geometry,
        nodes.Houseplant_7_1.geometry,
        nodes.Houseplant_7_2.geometry,
      ],
      painting: [
        nodes["Node-Mesh"].geometry,
        nodes["Node-Mesh_1"].geometry,
        nodes["Node-Mesh_2"].geometry,
        nodes["Node-Mesh_3"].geometry,
        nodes["Node-Mesh_4"].geometry,
        nodes["Node-Mesh_5"].geometry,
      ],
    }),
    [nodes]
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Screen"
        visible={roomVisible}
        geometry={nodes.Screen.geometry}
        position={[0.05, 0.67, -1.34]}
        rotation={[-0.3, -1.52, -0.24]}
        scale={0.01}
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>
      <group name="Room" visible={roomVisible}>
        <MergedMeshes
          name="Plane"
          scale={1.62}
          geometries={geometries.plane}
          material={textureMaterial}
        />

        <motion.group
          name="CoffeTable"
          position={[1.21, 0.37, 0.69]}
          rotation={[2.44, -1.55, 2.44]}
          scale={0}
          animate={{
            scale: section === 0 ? 1 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.coffeeTable}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="Cubone"
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 0.44 : 0,
          }}
          position={[0.6, 1.85, -1.28]}
          rotation={[-3.1, -0.3, -3.13]}
        >
          <MergedMeshes
            geometries={geometries.cubone}
            material={textureMaterial}
          />
        </motion.group>
        <MergedMeshes
          name="Desk"
          position={[-0.07, 0.09, -1.22]}
          rotation={[2.87, -1.55, 2.87]}
          scale={0.59}
          geometries={geometries.desk}
          material={textureMaterial}
        />
        <motion.group
          name="Speaker"
          position={[-1.23, 0.08, -1.18]}
          rotation={[-0.05, 0.78, 0.03]}
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 32.41 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.speaker}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="Switch"
          position={[0.36, 1.83, -0.02]}
          rotation={[0.05, 0.02, 0]}
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 0.06 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.switchConsole}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="iMac"
          position={[0.05, 0.67, -1.33]}
          rotation={[-0.3, -1.52, -0.24]}
          animate={{
            scale: section === 0 ? 0.01 : 0,
          }}
          scale={0}
        >
          <MergedMeshes
            geometries={geometries.imac}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="Cardboard_Boxes"
          position={[0.61, 0.09, 1.22]}
          animate={{
            scale: section === 0 ? 148.8 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.boxes}
            material={textureMaterial}
          />
        </motion.group>
        <motion.group
          name="Drum"
          position={[-0.98, 0.4, 0.67]}
          rotation={[-1.6, 0.04, -1.45]}
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 55.38 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.drum}
            material={textureMaterial}
          />
        </motion.group>
        <MergedMeshes
          name="Keyboard"
          position={[-0.01, 0.66, -1.15]}
          scale={0.16}
          geometries={geometries.keyboard}
          material={textureMaterial}
        />
        <motion.group
          name="Lamp"
          animate={{
            scale: section === 0 ? 0.26 : 0,
          }}
          position={[-0.38, 0.8, -1.33]}
          scale={[0, 0, 0]}
        >
          <MergedMeshes
            geometries={geometries.lamp}
            material={textureMaterial}
          />
        </motion.group>
        <MergedMeshes
          name="Shelf"
          position={[0.4, 1.46, -1.35]}
          scale={0.35}
          geometries={geometries.shelf}
          material={textureMaterial}
        />
        <MergedMeshes
          name="Shelf_Clutter"
          position={[-1.44, 1.27, 0.96]}
          rotation={[-0.93, -1.53, -0.94]}
          scale={56.33}
          geometries={geometries.shelfClutter}
          material={textureMaterial}
        />

        <motion.group
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 51.12 : 0,
          }}
          name="Houseplant"
          position={[1.36, 0.08, -1]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <MergedMeshes
            geometries={geometries.houseplant}
            material={textureMaterial}
          />
        </motion.group>
        <motion.mesh
          name="GamerChair"
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 64.99 : 0,
          }}
          geometry={nodes.GamerChair.geometry}
          material={textureMaterial}
          position={[-0.05, 0.32, -0.66]}
          rotation={[-1.57, 0, 2.92]}
        />
        <motion.group
          name="Painting"
          position={[-1.02, 1.46, -1.51]}
          rotation={[3.13, -0.02, -3.14]}
          scale={0.72}
          animate={{
            scale: section === 0 ? 1 : 0,
          }}
        >
          <MergedMeshes
            geometries={geometries.painting}
            material={textureMaterial}
          />
        </motion.group>
      </group>
    </group>
  );
}

useGLTF.preload(OFFICE_URL, DRACO_PATH);
useTexture.preload("textures/Baked.jpg");
